---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.test.crossplane.io
spec:
  group: test.crossplane.io
  names:
    kind: XCluster
    plural: xclusters
  connectionSecretKeys:
    - kubeconfig
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      # We intentionally have no schema. Crossplane will inject the bare
      # minimum XR machinery.
      openAPIV3Schema: {}